import type { Localized, PricingPlan } from "@/content/types";

export const pricingPlans: Localized<PricingPlan[]> = {
  tr: [
    {
      id: "launch",
      name: "Launch",
      subtitle: "Tek sube veya duzenli randevu trafigi yeni hizlanan ekipler icin.",
      price: "₺3.900",
      period: "/ ay",
      featured: false,
      ctaLabel: "Paketi Sec",
      features: [
        "Instagram ve WhatsApp gelen kutusu akisi",
        "Temel AI yanit senaryolari",
        "Randevu linki paylasimi",
        "Calisma saatleri disi otomasyon",
        "Standart onboarding destegi",
      ],
    },
    {
      id: "studio",
      name: "Studio",
      subtitle: "Yuksek mesaj hacmi ve daha guclu donusum akislari isteyen salonlar icin.",
      price: "₺6.900",
      period: "/ ay",
      featured: true,
      badge: "En cok tercih edilen",
      ctaLabel: "Hizmete Abone Ol",
      features: [
        "Tum Launch ozellikleri",
        "Daha gelismis AI niyet anlama",
        "Insan devir modu ve ekip notlari",
        "Mesajdan randevuya donusum akislari",
        "Oncelikli destek ve kurulum",
      ],
    },
    {
      id: "signature",
      name: "Signature",
      subtitle: "Birden fazla uzman, yogun operasyon ve ozel surecler icin esnek kurulum.",
      price: "₺9.900",
      period: "/ ay",
      featured: false,
      ctaLabel: "Teklif Al",
      features: [
        "Tum Studio ozellikleri",
        "Operasyonel akis ve kampanya kurgulari",
        "Cok adimli salon sureclerine ozel setup",
        "Premium onboarding planlamasi",
        "Buyumeye ozel strateji destegi",
      ],
    },
  ],
  en: [
    {
      id: "launch",
      name: "Launch",
      subtitle: "For single-location salons and teams that want faster response times without extra complexity.",
      price: "₺3,900",
      period: "/ month",
      featured: false,
      ctaLabel: "Choose plan",
      features: [
        "Shared Instagram and WhatsApp flow",
        "Core AI reply scenarios",
        "Booking link handoff",
        "After-hours automation",
        "Standard onboarding support",
      ],
    },
    {
      id: "studio",
      name: "Studio",
      subtitle: "For busy salons that need stronger conversion flows and better team control.",
      price: "₺6,900",
      period: "/ month",
      featured: true,
      badge: "Most popular",
      ctaLabel: "Subscribe",
      features: [
        "Everything in Launch",
        "More advanced intent understanding",
        "Human takeover and team notes",
        "Conversation-to-booking journeys",
        "Priority setup and support",
      ],
    },
    {
      id: "signature",
      name: "Signature",
      subtitle: "For larger teams, denser workflows, and a more tailored operational setup.",
      price: "₺9,900",
      period: "/ month",
      featured: false,
      ctaLabel: "Request proposal",
      features: [
        "Everything in Studio",
        "Operational workflow and campaign setups",
        "Custom implementation for salon processes",
        "Premium onboarding planning",
        "Growth-oriented strategic guidance",
      ],
    },
  ],
};
