import type { Localized, PricingPlan } from "@/content/types";

export const pricingPlans: Localized<PricingPlan[]> = {
  tr: [
    {
      id: "launch",
      name: "Launch",
      subtitle: "Tek şubeli ya da düzenli randevu trafiği hızlanan ekipler için.",
      price: "₺3.900",
      period: "/ ay",
      featured: false,
      ctaLabel: "Paketi Seç",
      features: [
        "Instagram ve WhatsApp mesaj akışı",
        "Temel yapay zekâ yanıt senaryoları",
        "Randevu linki paylaşımı",
        "Çalışma saatleri dışında otomasyon",
        "Standart kurulum desteği",
      ],
    },
    {
      id: "studio",
      name: "Studio",
      subtitle: "Yüksek mesaj hacmi ve daha güçlü dönüşüm akışları isteyen salonlar için.",
      price: "₺6.900",
      period: "/ ay",
      featured: true,
      badge: "En çok tercih edilen",
      ctaLabel: "Hizmete Abone Ol",
      features: [
        "Launch paketindeki tüm özellikler",
        "Daha gelişmiş niyet anlama",
        "İnsan devir modu ve ekip notları",
        "Mesajdan randevuya dönüşüm akışları",
        "Öncelikli destek ve kurulum",
      ],
    },
    {
      id: "signature",
      name: "Signature",
      subtitle: "Birden fazla uzmanı, yoğun operasyonu ve özel süreçleri olan salonlar için.",
      price: "₺9.900",
      period: "/ ay",
      featured: false,
      ctaLabel: "Teklif Al",
      features: [
        "Studio paketindeki tüm özellikler",
        "Operasyonel akış ve kampanya kurguları",
        "Çok adımlı salon süreçlerine özel kurulum",
        "Premium onboarding planlaması",
        "Büyümeye özel strateji desteği",
      ],
    },
  ],
  en: [
    {
      id: "launch",
      name: "Launch",
      subtitle: "For single-location salons and teams that want faster response times without extra complexity.",
      price: "₺3,900",
      period: "/ month",
      featured: false,
      ctaLabel: "Choose plan",
      features: [
        "Shared Instagram and WhatsApp flow",
        "Core AI reply scenarios",
        "Booking link handoff",
        "After-hours automation",
        "Standard onboarding support",
      ],
    },
    {
      id: "studio",
      name: "Studio",
      subtitle: "For busy salons that need stronger conversion flows and better team control.",
      price: "₺6,900",
      period: "/ month",
      featured: true,
      badge: "Most popular",
      ctaLabel: "Subscribe",
      features: [
        "Everything in Launch",
        "More advanced intent understanding",
        "Human takeover and team notes",
        "Conversation-to-booking journeys",
        "Priority setup and support",
      ],
    },
    {
      id: "signature",
      name: "Signature",
      subtitle: "For larger teams, denser workflows, and a more tailored operational setup.",
      price: "₺9,900",
      period: "/ month",
      featured: false,
      ctaLabel: "Request proposal",
      features: [
        "Everything in Studio",
        "Operational workflow and campaign setups",
        "Custom implementation for salon processes",
        "Premium onboarding planning",
        "Growth-oriented strategic guidance",
      ],
    },
  ],
};
